#!/bin/bash

x=1
base=1
y=$1

sum=0

while [ $x -le $y ]
do

#echo itteration $x
let x=x+1

echo divide by $base
sum=`echo "scale=1000; $sum + $base" | bc -l`

base=`echo "scale=1000; $base/2" | bc -l`



done

echo $sum
